name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: [stable]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.sdk }}
      - name: Get dependencies
        run: flutter pub get
      - name: Static analysis
        run: dart analyze
      - name: Run unit tests
        run: dart test test/unit --reporter expanded

  integration-tests:
    runs-on: ubuntu-latest
    needs: analyze-and-test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Get dependencies
        run: flutter pub get
      - name: Run integration tests (allowed to fail)
        run: dart test test/integration --reporter expanded
        continue-on-error: true
