name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  verify-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
      - name: Get dependencies
        run: flutter pub get
      - name: Static analysis
        run: dart analyze
      - name: Run unit tests
        run: dart test test/unit --reporter expanded
      - name: Pub publish (dry run)
        run: flutter pub publish --dry-run

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
